version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
       - ./development.sql:/docker-entrypoint-initdb.d/dump.sql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: embodied
       MYSQL_USER: root
       MYSQL_PASSWORD: secret

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./src/themes/embodied-kiddos:/var/www/html/wp-content/themes/embodied-kiddos
       - ./src/uploads:/var/www/html/wp-content/uploads
       - ./src/plugins:/var/www/html/wp-content/plugins
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_NAME: embodied
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: secret
       WORDPRESS_DEBUG: 1
       VIRTUAL_HOST: www.embodiedkiddos.com
       VIRTUAL_PORT: 8000
       LETSENCRYPT_HOST: www.embodiedkiddos.com
volumes:
    db_data:

networks:
  default:
    external:
      name: proxy
